#!/bin/bash

# Email Forwarding DNS Configuration Helper
# This script provides the DNS records needed for ImprovMX email forwarding

echo "=========================================="
echo "Email Forwarding DNS Configuration"
echo "Domain: reggiepangilinan.com"
echo "Service: ImprovMX"
echo "=========================================="
echo ""

echo "DNS Records to Add:"
echo "==================="
echo ""

echo "1. MX Records (Mail Exchange):"
echo "   Type: MX"
echo "   Name: @ (or root domain)"
echo "   Value: mx1.improvmx.com"
echo "   Priority: 10"
echo ""
echo "   Type: MX"
echo "   Name: @ (or root domain)"  
echo "   Value: mx2.improvmx.com"
echo "   Priority: 20"
echo ""

echo "2. SPF Record (Sender Policy Framework):"
echo "   Type: TXT"
echo "   Name: @ (or root domain)"
echo "   Value: \"v=spf1 include:_spf.improvmx.com ~all\""
echo ""

echo "3. Optional DMARC Record:"
echo "   Type: TXT"
echo "   Name: _dmarc"
echo "   Value: \"v=DMARC1; p=quarantine; rua=mailto:me@reggiepangilinan.com\""
echo ""

echo "Instructions:"
echo "============="
echo "NETLIFY DNS SETUP (Recommended):"
echo "1. Go to https://app.netlify.com/"
echo "2. Navigate to Team > Domains"
echo "3. Select reggiepangilinan.com"
echo "4. In DNS records section, click 'Add new record'"
echo "5. Add each MX and TXT record above"
echo "6. Wait 2-4 hours for Netlify DNS propagation"
echo ""
echo "ALTERNATIVE - Manual DNS Provider:"
echo "1. Log into your DNS provider"
echo "2. Navigate to DNS settings for reggiepangilinan.com"
echo "3. Add the MX and TXT records above"
echo "4. Save changes and wait for propagation (24-48 hours)"
echo ""
echo "IMPORTANT NETLIFY NOTES:"
echo "- Don't delete existing NETLIFY/A records (they're for your website)"
echo "- MX records can coexist with your site hosting"
echo "- Netlify does NOT provide built-in email forwarding"
echo "- You MUST use a third-party service like ImprovMX"
echo ""

echo "Verification Commands:"
echo "====================="
echo "Check MX records: dig MX reggiepangilinan.com"
echo "Check SPF record: dig TXT reggiepangilinan.com"
echo "Check DMARC:      dig TXT _dmarc.reggiepangilinan.com"
echo ""

echo "Setup URL: https://improvmx.com/"
echo "Documentation: $(dirname "$0")/../docs/setup/EMAIL_FORWARDING_IMPLEMENTATION.md"
